import { useState } from 'react';
import { SafeAreaView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { Button, COLORS, ErrorBox } from '../src/components/Ui';
import { request, type User } from '../src/lib/api';
import { saveUser } from '../src/lib/auth';
import { useAuth } from '../src/store/AuthContext';

export default function Settings(){const{token,user,refreshMe,logout}=useAuth();const[date,setDate]=useState(user?.birth_date??'');const[error,setError]=useState('');async function save(){try{const updated=await request<User>('/users/me/age',{method:'PATCH',body:JSON.stringify({birth_date:date})},token);await saveUser(updated);await refreshMe();setError('')}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить')}}return <SafeAreaView style={styles.screen}><View style={styles.header}><Text style={styles.headerText}>Настройки</Text></View><View style={styles.body}><Text style={styles.avatar}>●</Text><Text style={styles.username}>{user?.username}</Text><Text style={styles.label}>Дата рождения</Text><TextInput value={date} onChangeText={setDate} placeholder="YYYY-MM-DD" style={styles.input}/>{error?<ErrorBox text={error}/>:null}<Button onPress={save}>Сохранить возраст</Button><Button variant="danger" onPress={async()=>{await logout();router.replace('/auth')}}>Выйти из аккаунта</Button><Button variant="secondary" onPress={()=>router.back()}>Назад</Button></View></SafeAreaView>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:COLORS.paper},header:{height:68,backgroundColor:COLORS.yellow,borderBottomWidth:2,borderBottomColor:COLORS.ink,alignItems:'center',justifyContent:'center'},headerText:{fontSize:21,fontWeight:'900'},body:{padding:22,gap:14},avatar:{fontSize:82,color:COLORS.pink,textAlign:'center'},username:{fontSize:30,fontWeight:'900',textAlign:'center',marginBottom:12},label:{fontSize:14,fontWeight:'800'},input:{height:56,borderWidth:2,borderColor:'#BDBDBD',borderRadius:14,paddingHorizontal:14,fontSize:18,backgroundColor:'#fff'}})
