import { useEffect, useState } from 'react';
import { Image, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { WebView } from 'react-native-webview';
import { Button, COLORS, Loading } from '../../src/components/Ui';
import { request, type Movie } from '../../src/lib/api';
import { useAuth } from '../../src/store/AuthContext';

export default function SessionScreen(){
 const {id}=useLocalSearchParams<{id:string}>(); const {token}=useAuth(); const [movies,setMovies]=useState<Movie[]>([]); const [index,setIndex]=useState(0); const [error,setError]=useState(''); const [voting,setVoting]=useState(false); const [matchedMovie,setMatchedMovie]=useState<Movie|null>(null);
 async function load(){try{setMovies(await request<Movie[]>(`/sessions/${id}/movies?limit=8&exploration_ratio=0.25`,{},token))}catch(e){setError(e instanceof Error?e.message:'Не удалось загрузить фильмы')}}
 useEffect(()=>{load()},[id]); const movie=movies[index]; const trailer=movie?.trailer_url ? movie.trailer_url : null;
 async function vote(value:'LIKE'|'DISLIKE'|'SKIP'){if(!movie)return;setVoting(true);setError('');try{const result=await request<{matched:boolean;match:{id:string}|null}>(`/sessions/${id}/votes`,{method:'POST',body:JSON.stringify({movie_id:movie.id,value})},token);if(result.matched){setMatchedMovie(movie);return;} if(index+1<movies.length)setIndex(index+1);else {await load();setIndex(0);}}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить выбор')}finally{setVoting(false)}}
 if(matchedMovie)return <View style={styles.matchScreen}>{matchedMovie.backdrop_url?<Image source={{uri:matchedMovie.backdrop_url}} style={styles.matchBg}/>:null}<View style={styles.matchOverlay}/><View style={styles.matchCard}><Text style={styles.matchKicker}>EVERYONE AGREED</Text><Text style={styles.matchTitle}>Ваш фильм найден.</Text>{matchedMovie.poster_url?<Image source={{uri:matchedMovie.poster_url}} style={styles.matchPoster}/>:null}<Text style={styles.matchMovieTitle}>{matchedMovie.title}</Text><Text style={styles.matchCopy}>Похоже, на сегодня решение принято.</Text><Button onPress={()=>router.replace('/home')}>Вернуться</Button></View></View>;
 if(!movie)return error?<ScrollView contentContainerStyle={styles.center}><Text style={styles.error}>{error}</Text><Button onPress={load}>Обновить</Button></ScrollView>:<Loading/>;
 const embed = (()=>{if(!movie.trailer_url)return null;try{const u=new URL(movie.trailer_url);let vid=u.searchParams.get('v');if(!vid&&u.hostname.includes('youtu.be'))vid=u.pathname.slice(1);if(!vid&&u.pathname.includes('/embed/'))vid=u.pathname.split('/embed/')[1]?.split('/')[0];return vid?`https://www.youtube.com/embed/${vid}?autoplay=1&mute=1&playsinline=1&controls=1&rel=0`:null}catch{return null}})();
 return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Text style={styles.kicker}>NOW PLAYING · {index+1}/{movies.length}</Text><View style={styles.visual}>{embed?<WebView source={{uri:embed}} allowsInlineMediaPlayback mediaPlaybackRequiresUserAction={false} style={styles.webview}/>:movie.poster_url?<Image source={{uri:movie.poster_url}} style={styles.poster}/>:<View style={styles.fallback}><Text>NO POSTER</Text></View>}</View><View style={styles.info}><Text style={styles.title}>{movie.title}</Text><Text style={styles.meta}>{movie.genres.map(g=>g.name).join(' · ')}</Text><Text style={styles.meta}>{movie.release_date?.slice(0,4)??'—'} · {movie.vote_average?.toFixed(1)??'—'} / 10</Text>{movie.overview?<Text style={styles.overview}>{movie.overview}</Text>:null}<View style={styles.chips}>{movie.genres.map(g=><View key={g.id} style={styles.chip}><Text style={styles.chipText}>{g.name}</Text></View>)}</View></View><View style={styles.actions}><Button variant="danger" disabled={voting} onPress={()=>vote('DISLIKE')}>✕</Button><Button variant="secondary" disabled={voting} onPress={()=>vote('SKIP')}>↗</Button><Button disabled={voting} onPress={()=>vote('LIKE')}>♥</Button></View>{error?<Text style={styles.error}>{error}</Text>:null}</ScrollView>
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:COLORS.ink},content:{padding:14,gap:12,paddingBottom:40},center:{flex:1,alignItems:'center',justifyContent:'center',padding:20,gap:12},kicker:{color:'#aaa',fontSize:11,letterSpacing:2,fontWeight:'700'},visual:{width:'100%',aspectRatio:16/10,borderRadius:22,overflow:'hidden',borderWidth:2,borderColor:'#fff',backgroundColor:'#000'},webview:{flex:1,backgroundColor:'#000'},poster:{width:'100%',height:'100%',resizeMode:'cover'},fallback:{flex:1,alignItems:'center',justifyContent:'center'},info:{backgroundColor:'#F5F3ED',borderRadius:22,borderWidth:2,borderColor:'#111',padding:18,gap:8},title:{fontSize:36,fontWeight:'900',letterSpacing:-1.2,color:'#111'},meta:{fontSize:12,color:'#666'},overview:{fontSize:17,lineHeight:25,color:'#57544E',marginTop:8},chips:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:8},chip:{paddingHorizontal:10,paddingVertical:7,borderRadius:999,borderWidth:1.5,borderColor:'#111',backgroundColor:'#fff'},chipText:{fontSize:12,fontWeight:'800'},actions:{flexDirection:'row',gap:10},matchScreen:{flex:1,backgroundColor:'#111',padding:18,justifyContent:'center'},matchBg:{position:'absolute',top:0,left:0,right:0,bottom:0,width:'100%',height:'100%'},matchOverlay:{position:'absolute',top:0,left:0,right:0,bottom:0,backgroundColor:'rgba(17,17,17,.76)'},matchCard:{backgroundColor:'#F5F3ED',borderWidth:2,borderColor:'#111',borderRadius:28,padding:20,gap:12},matchKicker:{fontSize:11,letterSpacing:2,color:'#777',fontWeight:'800'},matchTitle:{fontSize:40,fontWeight:'900',letterSpacing:-1.5},matchPoster:{width:'100%',aspectRatio:2/3,borderRadius:18},matchMovieTitle:{fontSize:28,fontWeight:'900'},matchCopy:{fontSize:17,color:'#5D5A52',lineHeight:24},error:{color:'#8F1722',backgroundColor:'#FFE0E4',padding:12,borderRadius:12}}
)
